services:
  - type: web
    name: sentiment-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader punkt stopwords
    startCommand: python app.py
